/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mini_Project;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas
 */
public class Customer_Registration_DB_Table extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Registration_DB_Table
     */
    public Customer_Registration_DB_Table() {
        initComponents();
        Image icn = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\Water Billing System\\src\\Mini_Project\\Images\\icons8_plumbing_40px_1.png");
        setIconImage(icn);
        setLocation(180,10);
        setTitle("Water Billing System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        showbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        tf9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Counter TagNo", "Customer Full Name", "Sex", "Phone No", "Surrounding City", "Locality/Kebele", "Village", "House No"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1060, 310));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_update_64px.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 150, 50));

        showbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        showbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_table_48px_1.png"))); // NOI18N
        showbtn.setText("Show");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });
        getContentPane().add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 150, 50));

        searchbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_search_property_64px_1.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 150, 50));

        editbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        editbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_edit_property_64px.png"))); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        getContentPane().add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 150, 50));

        tf9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf9.setToolTipText("Enter CounterTagNo");
        getContentPane().add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 150, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Customer Full Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 140, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Counter TagNo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Phone No:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 90, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Sex: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("House No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Village:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 90, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Locality:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 90, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Surrounding City:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 120, 30));

        tf2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 170, 30));

        tf1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 170, 30));

        tf4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 170, 30));

        tf3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 170, 30));

        tf8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 170, 30));

        tf7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 170, 30));

        tf6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 170, 30));

        tf5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 170, 30));

        deletebtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_delete_bin_48px.png"))); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 140, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_return_16px.png"))); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 140, 50));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Customer Registration Database");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 330, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_80px.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, -1, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_80px.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, -1, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        try{
            String sql = "select * from customerregistration";
            ResultSet rs = db.s.executeQuery(sql);
            DefaultTableModel tm = (DefaultTableModel)table.getModel();
            tm.setRowCount(0);
            tf1.setText("");
            tf2.setText("");
            tf3.setText("");
            tf4.setText("");
            tf5.setText("");
            tf6.setText("");
            tf7.setText("");
            tf8.setText("");
            while(rs.next())
            {
                Object o [] = {rs.getString("CounterTagNo"),rs.getString("CustomerFullName"),rs.getString("Sex"),rs.getString("PhoneNumber"),
                rs.getString("SurroundingCity"),rs.getString("Locality"),rs.getString("Village"),rs.getString("HouseNumber")};
                tm.addRow(o);
            }
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_showbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        try{
            String sql = "select * from customerregistration where CounterTagNo = '"+tf9.getText()+"'";
            ResultSet rs = db.s.executeQuery(sql);
            DefaultTableModel tm = (DefaultTableModel)table.getModel();
            tm.setRowCount(0);
            if(rs.next()){
                
           // while(rs.next())
            
              Object o [] = {rs.getString("CounterTagNo"),rs.getString("CustomerFullName"),rs.getString("Sex"),rs.getString("PhoneNumber"),
                rs.getString("SurroundingCity"),rs.getString("Locality"),rs.getString("Village"),rs.getString("HouseNumber")};
                tm.addRow(o);  
            
            }
            else
            {
                 JOptionPane.showMessageDialog(rootPane,"Enter The Correct Counter TagNo","Water Billing System",JOptionPane.ERROR_MESSAGE);   
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Enter The Correct Counter TagNo","Water Billing System",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Main_Page();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        /*DefaultTableModel model = (DefaultTableModel) table.getModel();
        
          if(table.getSelectedRowCount() == 0)
          {
              JOptionPane.showMessageDialog(null,"There Is No Selected Data To Delete","",JOptionPane.OK_OPTION);
          }
          else
          {
         model.removeRow(table.getSelectedRow());
            JOptionPane.showMessageDialog(null,"Successfully Deleted"," ",JOptionPane.INFORMATION_MESSAGE);
        
          
          }
        */
        DBConnection db = new DBConnection();
        PreparedStatement pst;
        try{
            String sql = "delete from customerregistration where CounterTagNo = ?";
            pst = db.c.prepareStatement(sql);
            pst.setString(1,tf1.getText());
            int a = JOptionPane.showConfirmDialog(rootPane,"Are You Sure To Delete This Customer");
            if(a == JOptionPane.YES_OPTION)
            {
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
            pst.close();
            }
            else
            {
                
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e,"Water Billing System",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel tm = (DefaultTableModel)table.getModel();
        int sr = table.getSelectedRow();
        tf1.setText(tm.getValueAt(sr,0).toString());
        tf2.setText(tm.getValueAt(sr,1).toString());
        tf3.setText(tm.getValueAt(sr,2).toString());
        tf4.setText(tm.getValueAt(sr,3).toString());
        tf5.setText(tm.getValueAt(sr,4).toString());
        tf6.setText(tm.getValueAt(sr,5).toString());
        tf7.setText(tm.getValueAt(sr,6).toString());
        tf8.setText(tm.getValueAt(sr,7).toString());
        }catch(Exception e)
        {
          JOptionPane.showMessageDialog(this,"No Data Selected","Water Billing System",JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        PreparedStatement pst;
        try{
            if(tf1.getText().equals("")||tf2.getText().equals("")||tf3.getText().equals("")||tf4.getText().equals("")||tf5.getText().equals("")||tf6.getText().equals("")||tf7.getText().equals("")||tf8.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this,"Please Fill All The Datas","Water Billing Sysetm",JOptionPane.ERROR);
            }
            else
            {
            String sql = ("update customerregistration set CounterTagNo=?,CustomerFullName=?,Sex=?,PhoneNumber=?,"
                    + "SurroundingCity=?,Locality=?,Village=?,HouseNumber=? where CounterTagNo=?");
            pst = db.c.prepareStatement(sql);
            pst.setString(1,tf1.getText());
            pst.setString(2,tf2.getText());
            pst.setString(3,tf3.getText());
            pst.setString(4,tf4.getText());
            pst.setString(5,tf5.getText());
            pst.setString(6,tf6.getText());
            pst.setString(7,tf7.getText());
            pst.setString(8,tf8.getText());
            pst.setString(9,tf1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Updated","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(Exception e)
        {
          JOptionPane.showMessageDialog(this,"Please Fill All The Datas","Water Billing System",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration_DB_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration_DB_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration_DB_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Registration_DB_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Registration_DB_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
