/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mini_Project;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas
 */
public class Login_DB extends javax.swing.JFrame {

    /**
     * Creates new form Login_DB
     */
    public Login_DB() {
        initComponents();
        Image icn = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\Water Billing System\\src\\Mini_Project\\Images\\icons8_plumbing_40px_1.png");
        setIconImage(icn);
        setTitle("Water Billing System");
        setLocation(200,80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        showbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        returnbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "E-mail", "Adress", "User Name", "Password", "Access Level"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 890, 160));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_update_16px.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 110, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Last Name: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("E-mail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("User Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 110, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Access Level:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 110, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 110, -1));

        tf7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 130, 30));

        tf1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, 30));

        tf2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, 30));

        tf3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 130, 30));

        tf4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 130, 30));

        tf5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 130, 30));

        tf6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 130, 30));

        showbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        showbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_database_view_16px.png"))); // NOI18N
        showbtn.setText("Show");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });
        getContentPane().add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, 40));

        editbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        editbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_edit_16px.png"))); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        getContentPane().add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 90, 40));

        deletebtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_delete_database_16px.png"))); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 110, 40));

        returnbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        returnbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_return_16px.png"))); // NOI18N
        returnbtn.setText("Return");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 110, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Login Database");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 70, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 50, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 70, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 70, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 70, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 70, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        try{
            String sql = "select * from login";
            ResultSet rs = db.s.executeQuery(sql);
            DefaultTableModel tm = (DefaultTableModel)table.getModel();
            tm.setRowCount(0);
            tf1.setText("");
            tf2.setText("");
            tf3.setText("");
            tf4.setText("");
            tf5.setText("");
            tf6.setText("");
            tf7.setText("");
            while(rs.next())
            {
                Object o [] = {rs.getString("FirstName"),rs.getString("LastName"),rs.getString("Email"),rs.getString("Adress")
                ,rs.getString("UserName"),rs.getString("Password"),rs.getString("AccessLevel")};
                tm.addRow(o);
            }
            
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_showbtnActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"....Save Water....","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_returnbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel tm = (DefaultTableModel)table.getModel();
        int sr = table.getSelectedRow();
        
        tf1.setText(tm.getValueAt(sr,0).toString());
        tf2.setText(tm.getValueAt(sr,1).toString());
        tf3.setText(tm.getValueAt(sr,2).toString());
        tf4.setText(tm.getValueAt(sr,3).toString());
        tf5.setText(tm.getValueAt(sr,4).toString());
        tf6.setText(tm.getValueAt(sr,5).toString());
        tf7.setText(tm.getValueAt(sr,6).toString());
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"No Data Selected","Water Billing System",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        PreparedStatement pst;
        try{
            String sql = "update login set Firstname =?,Lastname =?,Email =?,Adress=?,Username=?,Password=?,AccessLevel=? where Email=? ";
           
            if(tf1.getText().equals("")||tf2.getText().equals("")||tf3.getText().equals("")||tf4.getText().equals("")||tf5.getText().equals("")||tf6.getText().equals("")||tf7.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please Fill All The Datas","Water Billing System",JOptionPane.ERROR);
            }
            else
            {
               pst = db.c.prepareStatement(sql);
               pst.setString(1,tf1.getText());
               pst.setString(2,tf2.getText());
               pst.setString(3,tf3.getText());
               pst.setString(4,tf4.getText());
               pst.setString(5,tf5.getText());
               pst.setString(6,tf6.getText());
               pst.setString(7,tf7.getText());
               pst.setString(8,tf3.getText());
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Successfully Updated","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Please Fill All The Datas","Water Billing System",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        PreparedStatement pst;
        try{
            String sql = "delete from login where Password = ?";
            pst = db.c.prepareStatement(sql);
            pst.setString(1,tf6.getText());
            int a = JOptionPane.showConfirmDialog(rootPane,"Are You Sure To Delete?");
            if(a == JOptionPane.YES_OPTION)
            {
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
            db.c.close();
            pst.close();
            }
            else{
                
            }
        }catch(Exception e)
        {
            
        }
            
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_DB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnbtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
