/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mini_Project;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas
 */
public class Monthly_Payment_RegistrationDB extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public Monthly_Payment_RegistrationDB() {
        initComponents();
        Image icn = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Thomas\\Documents\\NetBeansProjects\\Water Billing System\\src\\Mini_Project\\Images\\icons8_plumbing_40px_1.png");
        setIconImage(icn);
        setTitle("Water Billing System");
        setLocation(270,80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnshow = new javax.swing.JButton();
        tf5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Counter TagNo", "LastReading", "CurrentReading", "Month", "Status"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, 170));

        btnshow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_database_view_16px.png"))); // NOI18N
        btnshow.setText("Show");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });
        getContentPane().add(btnshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 100, 40));

        tf5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf5.setToolTipText("Enter Counter TagNo");
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 150, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Last Reading:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Counter TagNo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Current Reading:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Month:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        tf2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 120, 30));

        tf1.setEditable(false);
        tf1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 30));

        tf3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 120, 30));

        tf4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Monthly Payment Registration Database");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 330, 30));

        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_update_16px.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 100, 40));

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_search_16px.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, 40));

        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_edit_16px.png"))); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 100, 40));

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_delete_database_16px.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 100, 40));

        btnreturn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_return_16px.png"))); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 50, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_plumbing_48px.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mini_Project/Images/icons8_water_48px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 50, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        try{
            String sql = "select * from payment";
            ResultSet rs = db.s.executeQuery(sql);
            DefaultTableModel tm = (DefaultTableModel)table.getModel();
            tm.setRowCount(0);
            tf1.setText("");
            tf2.setText("");
            tf3.setText("");
            tf4.setText("");
            while(rs.next())
            {
                Object o [] = {rs.getString("CounterTagNo"),rs.getInt("LastReading"),rs.getInt("CurrentReading"),rs.getString("Month"),rs.getString("Status")};
                tm.addRow(o);
                
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"There is No Data In The Database","Water Billing System",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnshowActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        PreparedStatement pst;
        if(tf2.getText().equals("")||tf3.getText().equals("")||tf4.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please Fill All The Datas","Water Billing System",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        try{
            String sql = "update payment set CurrentReading=?,LastReading=? where CounterTagNo=? and LastReading=?";
            pst = db.c.prepareStatement(sql);
            pst.setString(1,tf3.getText());
            pst.setString(2,tf4.getText());
            pst.setString(3,tf1.getText());
            pst.setString(4,tf4.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Updated","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        try{
            String sql = "select * from payment where CounterTagNo = '"+tf5.getText()+"'";
            ResultSet rs = db.s.executeQuery(sql);
            DefaultTableModel tm = (DefaultTableModel)table.getModel();
            tm.setRowCount(0);
           
            while(rs.next())
            {
            Object o []= {rs.getString("CounterTagNo"),rs.getString("LastReading"),rs.getString("CurrentReading"),rs.getString("Month"),rs.getString("Status")};
            tm.addRow(o);
            }
            
        }catch(Exception e)
        {
          JOptionPane.showMessageDialog(rootPane,"Enter The Correct Counter TagNo","Error",JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
      DefaultTableModel tm = (DefaultTableModel)table.getModel();
      int SelectedRows = table.getSelectedRow();
      tf1.setText(tm.getValueAt(SelectedRows,0).toString());
      tf2.setText(tm.getValueAt(SelectedRows,3).toString());
      tf3.setText(tm.getValueAt(SelectedRows,2).toString());
      tf4.setText(tm.getValueAt(SelectedRows,1).toString());
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"No Data Selected","Water Billing System",JOptionPane.ERROR);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         DBConnection db = new DBConnection();
        PreparedStatement pst;
        try{
            String sql = "delete from payment where CounterTagNo = ? and CurrentReading = ?";
            pst = db.c.prepareStatement(sql);
            pst.setString(1,tf1.getText());
            pst.setString(2, tf3.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Main_Page();
    }//GEN-LAST:event_btnreturnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"....Save Water....","Water Billing System",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monthly_Payment_RegistrationDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monthly_Payment_RegistrationDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monthly_Payment_RegistrationDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monthly_Payment_RegistrationDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monthly_Payment_RegistrationDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
